services:
  web:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"

    # Perfil de desenvolvimento
    profiles: ["dev"]
    command: python wsgi.py
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  web-prod:
    build: .
    container_name: flask_app_prod
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"

    # Perfil de produção
    profiles: ["prod"]
    command: gunicorn -w 4 -b ${FLASK_RUN_HOST}:${FLASK_RUN_PORT} wsgi:app
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0