services:
  web-dev:
    build: .
    container_name: flask_app_dev
    volumes:
      - .:/app
    env_file:
      - .env.dev
    ports:
      - "5001:5000"
    profiles: ["dev"]
    command: python wsgi.py
    depends_on:
      - mysql-dev

  mysql-dev:
    image: mysql:8.0
    container_name: mysql_db_dev
    env_file:
      - .env.dev
    volumes:
      - db_data-dev:/var/lib/mysql
    ports:
      - "3307:3306"
    profiles: ["dev"]

  web-prod:
    build: .
    container_name: flask_app_prod
    volumes:
      - .:/app
    env_file:
      - .env.prod
    ports:
      - "5002:5000"
    profiles: ["prod"]
    depends_on:
      - mysql-prod
  
  mysql-prod:
    image: mysql:8.0
    container_name: mysql_db_prod
    env_file:
      - .env.prod
    volumes:
      - db_data-prod:/var/lib/mysql
    ports:
      - "3308:3306"
    profiles: ["prod"]
  
volumes:
  db_data-dev:
  db_data-prod: