services:
  web-dev:
    build: .
    container_name: flask_app_dev
    volumes:
      - .:/app
    env_file:
      - .env.dev
    ports:
      - "5001:5000"
    profiles: ["dev"]
    command: python wsgi.py
    depends_on:
      - mysql-dev

  mysql-dev:
    image: mysql:8.0
    container_name: mysql_db_dev
    env_file:
      - .env.dev
    volumes:
      - db_data-dev:/var/lib/mysql
    profiles: ["dev"]

  web-prod:
    build: .
    container_name: flask_app_prod
    volumes:
      - .:/app
    env_file:
      - .env.prod
    profiles: ["prod"]
    depends_on:
      - mysql-prod
  
  mysql-prod:
    image: mysql:8.0
    container_name: mysql_db_prod
    env_file:
      - .env.prod
    volumes:
      - db_data-prod:/var/lib/mysql
    profiles: ["prod"]
  
  nginx:
    image: nginx:latest
    container_name: nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web-prod
    profiles: ["prod"]
  
volumes:
  db_data-dev:
  db_data-prod: