[default]
TITLE = 'APP - DOCKER'
EXTENSIONS = [
    'app.ext.database:init_app',
    'app.ext.migration:init_app',
    'app.seeders:init_app',
    'app.blueprints.webui:init_app'
]

[development]
DEBUG = true

[production]
DEBUG = false

# secrets.toml
# SECRET_KEY =
# SQLALCHEMY_DATABASE_URI = "mysql+pymysql://user:pass@host:3306/db"