[default]
DEBUG = false
TITLE = 'APP - DOCKER'
EXTENSIONS = [
    'app.ext.database:init_app',
    'app.ext.migration:init_app',
    'app.seeders:init_app',
    'app.blueprints.webui:init_app'
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}"

[production]
DEBUG = false
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}"


# secrets.toml
# [default]

# [development]
# SECRET_KEY = "python -c 'import secrets; print(secrets.token_hex())'"

# [production]
# SECRET_KEY = "python -c 'import secrets; print(secrets.token_hex())'"